---@class SwapItemsPayload
---@field source number
---@field action 'move' | 'stack' | 'swap' | 'give'
---@field fromInventory table | string | number
---@field toInventory table | string | number
---@field fromType 'string'
---@field toType 'string'
---@field fromSlot table
---@field toSlot table | number
---@field count number
